# Environment
env_id: PushCube-v1
obs: state
modality: state
action_dim: 8
num_envs: 4
num_eval_envs: 1
steps: 1000000

# ManiSkill3 Specific Blocks
env_cfg:
  env_id: ${env_id}
  num_envs: ${num_envs}
eval_env_cfg:
  env_id: ${env_id}
  num_envs: ${num_eval_envs}

# Evaluation
eval_freq: 25000
eval_episodes: 10
save_freq: 100000
work_dir: logs
exp_name: ms3_distill_1M
render: false

# Training
[cite_start]batch_size: 256 # Optimal for multi-task knowledge distillation [cite: 149, 221]
lr: 0.0003
enc_lr_scale: 0.1
grad_clip_norm: 20
rho: 0.5
entropy_coef: 0.0001
consistency_coef: 20
reward_coef: 0.1
value_coef: 0.1
[cite_start]distill_coef: 0.4 # Optimal weight for teacher guidance [cite: 118]
seed: 1

# Two-hot encoding
vmax: 10
vmin: -10
num_bins: 101
bin_size: 0.2

# Model
model_size: 1
latent_dim: 128
num_enc_layers: 2
enc_dim: 256
mlp_dim: 384
num_q: 2
true_latent_dim: 128

# Planning
mpc: true
horizon: 5
num_samples: 512
iterations: 6
num_elites: 64
num_pi_trajs: 24
temperature: 0.5
min_std: 0.05
max_std: 2
discount_denom: 5
discount_min: 0.95
discount_max: 0.995

# Distillation
checkpoint: /root/td-mpc-opt/tdmpc2/models/multitask/mt30-317M.pt
multitask: false
task_dim: 96

# Infrastructure
device: cuda
save_csv: true
wandb: false
wandb_project: none
wandb_entity: none