defaults:
    - override hydra/launcher: submitit_local

# environment
task: dog-run
obs: state

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 1_000_000

# training
steps: 300000 # 290_000 # 30M
batch_size: 256 # 1024
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 30000 # 10-20% of steps
exp_name: multi_distill_mt30_317to1M
data_dir: /home/dmytrok/Desktop/tdmpc2/tdmpc2/data/mt30

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# distillation
distillation_temperature: 2.0
distillation_weight: 0.5 # [0.1..1]

# architecture
model_size: ???
### 317M
num_enc_layers: 5
enc_dim: 4096
num_channels: 32
mlp_dim: 4096  
latent_dim: 1376 
task_dim: 96
num_q: 8
### 48M
# num_enc_layers: 4
# enc_dim: 1792
# num_channels: 32
# mlp_dim: 1792 # 512 384 
# latent_dim: 768 # 512 128
# task_dim: 96
# num_q: 5 # 5 2
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: worldmodels
wandb_entity: dmytrokuzmenko
wandb_silent: false
disable_wandb: false # true
save_csv: true

# misc
save_video: false # true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???  
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???