# environment
task: mt30
obs: state

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: ???

# training
steps: 200_000
batch_size: 1024
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20 # 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1000000 
exp_name: mt30_dist045_BS128_200K_steps_20241012
data_dir: /mnt/nas0/mt30/data/mt30

# planning
mpc: true
iterations: 6 # 6
num_samples: 512 # 512
num_elites: 64 # 64
num_pi_trajs: 24
horizon: 3 
min_std: 0.05
max_std: 2
temperature: 0.5 # 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4 # 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# distillation
distillation_temperature: 2.0
distillation_weight: 0.5

# architecture
model_size: 1
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 384
latent_dim: 128
task_dim: 96
num_q: 2
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: worldmodels
wandb_entity: dmytrokuzmenko
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: false
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???  
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???