# environment
task: maniskill3
obs: state  

# evaluation
checkpoint: /root/td-mpc-opt/tdmpc2/models/models--oleksandr-severhin--td-mpc-opt/snapshots/d152d673a316319defb2484794c8b03a20f9d261/mt30_1M_steps_50_decrease_final.pt
eval_episodes: 10
eval_freq: ???

# training
steps: 25_000 # 50_000. 100_000, 200_000, 337_000, 1_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20 # 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 500_000 # 1_000_000
exp_name: maniskill3_eval
data_dir: /root/td-mpc-opt/data/maniskill3

# distillation
distillation:
  schedule: "cosine_decay"
  d_coef: 0.4

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# distillation
distillation_temperature: 2.0
distillation_weight: 0.5

# architecture
model_size: 1
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 384
latent_dim: 128
task_dim: 96
num_q: 2
dropout: 0.01
simnorm_dim: 8

maniskill3:
  tasks:
    - "PickCube-v1"
    - "StackCube-v1"
    - "PegInsertionSide-v1"
    - "PlugCharger-v1"
    - "PushCube-v1"
    - "TurnFaucet-v1"
    - "OpenCabinetDoor-v1"
    - "OpenCabinetDrawer-v1"
    - "PushChair-v1"
    - "MoveBucket-v1"
  
  # Environment configuration
  env_kwargs:
    obs_mode: "state"  # or "rgbd", "pointcloud"
    control_mode: "pd_ee_delta_pose"  # or "pd_joint_delta_pos", "pd_joint_pos"
    render_mode: "rgb_array"
    sim_freq: 500
    control_freq: 20
    max_episode_steps: 200
    
  # Observation space settings (will be populated automatically)
  obs_space_type: "dict" 
  
  # Action space settings
  action_space_type: "continuous"
  
  # Evaluation specific settings
  eval_env_kwargs:
    render_mode: "human" 
    
  # GPU settings for ManiSkill 3
  sim_backend: "gpu"  
  num_envs: 1  # Number of parallel environments (increase for faster evaluation)

# logging
wandb_project: td-mpc-maniskill3
wandb_entity: ???
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: true  
save_agent: true
seed: 1

work_dir: ???
task_title: ???
multitask: true  # ManiSkill 3 supports multi-task evaluation
tasks: ???  
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???